# This is a basic workflow to help you get started with Actions

name: getEUdata-and-publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 12 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
#Modifies default permission granted to GITHUB_TOKEN (Not fully sure if and what needed though)  
permissions:
  contents: read
  issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: rocker/verse
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Every time
        run: echo "This step will always run" 
      # Load repo
      - uses: actions/checkout@v3
      - run: git version          
      # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("rvest")'
      # Run R script 
      # chmod: ubuntu command, makes script executable
      - name: Run script to knit rmd file
        run: |
          chmod +x knit_readme_eufunding.R 
          knit_readme_eufunding.R
      # List all files in directory (l-longform  a-all h-human readable)     
      - name: List all file  
        run: ls -lah  
      # Commit files
      - name: Commit files
        run: |
          git config --global --add safe.directory /vioannis/h4sci-gha-demo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/*
          git commit -am "add data"
          git push 
      
