# This is a basic workflow to help you get started with Actions

name: getEUdata-and-publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 12 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
#Modifies default permission granted to GITHUB_TOKEN (Not fully sure if and what needed though)  
#permissions:
 # contents: read/write
 # issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: rocker/verse
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Every time
        run: echo "This step will always run" 
      # Load repo
      - uses: actions/checkout@v3
      - run: git version
      - run: |
          git config --global --add safe.directory /__w/eu-funding/eu-funding
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
      - run: rm -rf README.md
      # Set-up R
      - name: Install packages
        run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'install.packages("eurostat")'
          Rscript -e 'install.packages("httr")'
          Rscript -e 'install.packages("jsonlite")'
          Rscript -e 'install.packages("RSocrata")'
          Rscript -e 'install.packages("ggplot2")'
          Rscript -e 'install.packages("dplyr")'
          Rscript -e 'install.packages("sf")'
          Rscript -e 'install.packages("rnaturalearth")'
          Rscript -e 'install.packages("rnaturalearthdata")'
          Rscript -e 'install.packages("geometry")'
      # Run R script 
      - run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      # List all files in directory (l-longform  a-all h-human readable)     
      - name: List all file  
        run: ls -lah  
      # Commit files
      - name: Commit files
        run: |
          git add README.md
          git commit -m "Update README.md via GH Actions"
          git push

      
